# Generated by Django 5.1.3 on 2024-11-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_farmer_project_financialreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='project',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
