# Generated by Django 5.1.3 on 2024-11-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_farmer_project_financialreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='role',
        ),
    ]
