# Generated by Django 5.1.3 on 2024-11-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_farmer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectImage',
            field=models.ImageField(blank=True, null=True, upload_to='projectImages/'),
        ),
    ]
