# Generated by Django 5.1.3 on 2024-11-19 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_funds',
            new_name='target_funds',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profit',
        ),
        migrations.AddField(
            model_name='farmer',
            name='photoProfile',
            field=models.ImageField(blank=True, null=True, upload_to='farmerPictures/'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Persentase keuntungan dalam rentang 0-100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
