# Generated by Django 5.1.3 on 2024-11-22 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_total_funds_project_target_funds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('e_wallet', 'E-Wallet'), ('credit_card', 'Credit Card')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('withdraw', 'Tarik Dana'), ('deposit', 'Setor Dana')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('success', 'Berhasil'), ('failed', 'Gagal')], default='success', max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
